### ISSUE TITLE
[Helios Solarized Light] Borders are too dark

### ISSUE THREAD

**Issue by svipas** [santoso-wijaya/vscode-helios-selene#10]
I like the way built-in Solarized Light shows borders they aren't too dark compared to Helios Solarized Light. My suggestion would be to use a little bit lighter color.

# Helios Solarized Light

<img width="697" alt="image" src="https://github.com/santoso-wijaya/vscode-helios-selene/assets/10441177/d138de61-1377-4fbc-8173-f952464a5148">

<img width="285" alt="image" src="https://github.com/santoso-wijaya/vscode-helios-selene/assets/10441177/0a336baa-394d-4107-b008-3d6156c587dd">

# Built-in Solarized Light

<img width="1391" alt="image" src="https://github.com/santoso-wijaya/vscode-helios-selene/assets/10441177/873b740e-4b0e-4987-bea4-a446f05ecd82">

**Comment by santoso-wijaya** [comment]
Thank you for the feedback! I'll dim them in the next patch.

**Comment by svipas** [comment]
Thank you ❤️

**Comment by svipas** [comment]
@santoso-wijaya It is way better now. I suggest to dim these as well or maybe use exactly same color:

<img width="479" alt="image" src="https://github.com/santoso-wijaya/vscode-helios-selene/assets/10441177/916b35da-e55e-4452-9b2a-bfb724bf3fe9">

**Comment by santoso-wijaya** [comment]
I think I prefer to set it to the same `{{ active_color }}` to be consistent with other active panels/tabs coloring.

![image](https://github.com/santoso-wijaya/vscode-helios-selene/assets/157527329/f082e09b-553e-4533-b8f1-276f5294171a)

**Comment by svipas** [comment]
Looks very good 👍
