### ISSUE TITLE
[Helios Solarized Light] JSX component props & HTML attributes color

### ISSUE THREAD

**Issue by svipas** [santoso-wijaya/vscode-helios-selene#11]
I'm not quite sure if it's a good idea to use exactly same color of functions to JSX component props & HTML attributes. Italic is fine since it gives a distinguish, but maybe there's a different color which can be used, for e.g. like built-in Solarized Light does (but with better contrast)?

**Comment by santoso-wijaya** [comment]
Thanks for filing an issue! I tweaked the shades and colors for the next patch.

**Comment by svipas** [comment]
Thank you ❤️
