### ISSUE TITLE
[Helios Solarized Light] Use same color for different types of comments

### ISSUE THREAD

**Issue by svipas** [santoso-wijaya/vscode-helios-selene#12]
<img width="128" alt="image" src="https://github.com/santoso-wijaya/vscode-helios-selene/assets/10441177/867185a2-f868-473e-b6d3-5763a3201b48">

I suggest to use exactly same color for all type of comments which is #92A1A1. Because now that green (#8D9800) is exactly the same as keywords, types, etc.

**Comment by santoso-wijaya** [comment]
Ah, I missed that. Thanks for noticing.

**Comment by svipas** [comment]
Thank you ❤️
