### ISSUE TITLE
[Helios Solarized Light] No color for 'new' keyword in JS/TS

### ISSUE THREAD

**Issue by svipas** [santoso-wijaya/vscode-helios-selene#13]
There's no color for `new` keyword in JS/TS. My suggestion would be to add it like it is in built-in Solarized Light.

<img width="148" alt="image" src="https://github.com/santoso-wijaya/vscode-helios-selene/assets/10441177/a25d68d0-6b71-4586-97c0-a9a18e52c99a">

**Comment by santoso-wijaya** [comment]
Fixing this in the next patch. Thanks!

**Comment by svipas** [comment]
Thank you ❤️
