### ISSUE TITLE
[Helios Solarized Light] Different color for classes in JS/TS

### ISSUE THREAD

**Issue by svipas** [santoso-wijaya/vscode-helios-selene#14]
Currently in JS/TS classes use exactly same color as function, maybe there's some different color which can be used for classes? Built-in Solarized Light has a different color.

<img width="168" alt="image" src="https://github.com/santoso-wijaya/vscode-helios-selene/assets/10441177/b65462bf-f093-4122-be76-833703ed4474">

**Comment by svipas** [comment]
Thank you ❤️

**Comment by svipas** [comment]
@santoso-wijaya I'm not quite sure if I like the bold style for keywords, classes and types. It just adds too much noise. My suggestion would be to remove bold as it was before. I see you're already using a little bit different color for classes and functions and that should be enough.

**Comment by svipas** [comment]
# After

<img width="215" alt="image" src="https://github.com/santoso-wijaya/vscode-helios-selene/assets/10441177/e6950284-4625-4dd0-b834-a21c1896a5d1">

<img width="486" alt="image" src="https://github.com/santoso-wijaya/vscode-helios-selene/assets/10441177/090695cd-3817-4f0b-bd99-72d3f0e2666a">

<img width="358" alt="image" src="https://github.com/santoso-wijaya/vscode-helios-selene/assets/10441177/478cc0d2-d459-48a6-b83f-3dcf57585ccd">

# Before

<img width="222" alt="image" src="https://github.com/santoso-wijaya/vscode-helios-selene/assets/10441177/4e953040-d642-42e2-ac89-5778658d3b0a">

<img width="486" alt="image" src="https://github.com/santoso-wijaya/vscode-helios-selene/assets/10441177/6062c87c-845b-48b2-8528-07ca2437e808">

<img width="352" alt="image" src="https://github.com/santoso-wijaya/vscode-helios-selene/assets/10441177/9e8d47fa-a0f7-4170-b5a4-752d542a0d2f">

@santoso-wijaya Way better before for me to be honest + text was more readable inside JSX components look into "Hello world" (I don't think blue makes sense, but now it is harder to see)

**Comment by svipas** [comment]
I really like this theme, way better than built-in Solarized Light and it really helps me stay in focus, sorry if I sound annoying regardless these changes, but theme is really important to me and I see care you about it too, so I hope we will find a compromise to make it even better 🤝

**Comment by santoso-wijaya** [comment]
Noted, thanks for the feedback. I experimented with the uncolored blue for the keywords because I saw that the default solarized color theme does that.

I'm reverting the bold styling. The class/function color differentiation in javascript should remain (as long as there's a semantic lsp that is) with red/blue.

**Comment by svipas** [comment]
I made sure that I have enabled semantic coloring, but after 0.3.2 I still see some problems.

#### Classes and functions still have exactly same color blue

<img width="167" alt="image" src="https://github.com/santoso-wijaya/vscode-helios-selene/assets/10441177/12089e4e-4235-4be4-a9d9-28d9635d1d12">

What about using color for classes and interfaces would be: `#bb8801`?

#### Keywords are orange now instead of yellow as before

<img width="324" alt="image" src="https://github.com/santoso-wijaya/vscode-helios-selene/assets/10441177/af055191-c055-4ca1-8cf3-58f8b47a7b9d">

My suggestion would be to revert back color as it was: `#8d9800`

#### `null` and `undefined` are same as constant variable

<img width="97" alt="image" src="https://github.com/santoso-wijaya/vscode-helios-selene/assets/10441177/cfe449f2-c8f3-41ab-96f4-3322ff7e9d07">

Maybe it should be changed like in built-in Solarized Light?

#### JSX components color

<img width="383" alt="image" src="https://github.com/santoso-wijaya/vscode-helios-selene/assets/10441177/c85ce5b9-f2c3-4e41-a2a5-95d64854a087">

In my opinion they should be like in built-in Solarized Light yellow `#8d9800`, but kept blue `#008DD1` if its HTML tag.

**Comment by svipas** [comment]
@santoso-wijaya This how it looks now with changes I made

```json
	"editor.tokenColorCustomizations": {
		"textMateRules": [
			{
				"scope": "support.class.component",
				"settings": {
					"foreground": "#8d9800"
				}
			},
			{
				"scope": "constant.language",
				"settings": {
					"foreground": "#BB8801"
				}
			},
			{
				"scope": ["storage.type", "keyword.control", "keyword.control.import", "storage"],
				"settings": {
					"foreground": "#8d9800"
				}
			}
		]
	},
	"editor.semanticTokenColorCustomizations": {
		"rules": {
			"class": "#bb8801",
			"type": "#bb8801",
			"interface": "#bb8801"
		}
	},
```

<img width="251" alt="image" src="https://github.com/santoso-wijaya/vscode-helios-selene/assets/10441177/1ff73318-b6bb-4aee-b9bb-ec546e82c8c9">

<img width="382" alt="image" src="https://github.com/santoso-wijaya/vscode-helios-selene/assets/10441177/1abfb068-0deb-4e28-bbff-8c97f17bde72">

**Comment by santoso-wijaya** [comment]
I made the tweaks to be applied generically for all languages, not just js/ts/jsx.

Separating class/type/interface (as one color) from method/function (diff color) makes sense to me.

**Comment by svipas** [comment]
@santoso-wijaya Sounds very good. Can't wait to test it out!

**Comment by svipas** [comment]
@santoso-wijaya Still some issues found in 0.3.3

#### Now class and keywords have exactly same color which makes it harder to read: `class Bar extends Foo {}`

<img width="235" alt="image" src="https://github.com/santoso-wijaya/vscode-helios-selene/assets/10441177/c0778274-515b-4257-91c2-a36f5c03735d">

<details>
<summary>Code</summary>

```ts
class Foo {}

class Bar extends Foo {}

function Baz() {

}

interface Something {}

const isThisFn = () => {}

type SomeText = 'string'

function convert(type: SomeText) {}

const isTrue = true

const isNull = null
```
</details>

#### Interface has separate red color which is great, but then type has same color as keywords, it should be aligned:

<img width="162" alt="image" src="https://github.com/santoso-wijaya/vscode-helios-selene/assets/10441177/abaf7a71-d1ce-4316-ae74-d2953dff2a0d">

<details>
<summary>Code</summary>

```ts
interface Something {}
type SomeText = 'string'
```
</details>

#### Keywords such as `private readonly` have exactly same color as classes so not sure if that helps with readability:

<img width="233" alt="image" src="https://github.com/santoso-wijaya/vscode-helios-selene/assets/10441177/69115f84-f69b-4552-bf03-53c47e4d0ecc">

<details>
<summary>Code</summary>

```ts
class Bar {}

class Foo {
	private readonly bar: Bar

	constructor() {
		console.log(this.bar)
	}
}
```
</details>

**Comment by santoso-wijaya** [comment]
Hm, I'll set up a jsx sample project to tweak things further later today.

**Comment by santoso-wijaya** [comment]
How's this? 
![image](https://github.com/santoso-wijaya/vscode-helios-selene/assets/157527329/201af64b-47dd-42ec-8914-7f49cc031b81)


I set class and type names to {{ green }}. Interface names remain distinct as {{ orange }}, and method/function names as {{ blue }}.

Keywords are mostly in {{ yellow }}.

**Comment by svipas** [comment]
@santoso-wijaya Now I have zero complains, looks awesome!

One small thing though I see that `interface` (red) and `type` (orange) have different coloring in TS, but maybe let's keep it as it is?

**Comment by svipas** [comment]
@santoso-wijaya I see you made changes in 0.3.7 I checked it out, voila everything looks amazing. Thanks for fixing out all issues I reported, I really appreciate it. Right now this is best Solarized Theme in VS Code 👏

**Comment by santoso-wijaya** [comment]
@svipas Thanks for running it through its paces! Do try the Selenized variant, too. I think it has better color contrasts and accents.
