### ISSUE TITLE
[Helios Solarized Light] Terminal inline suggestion text hard to distinguish

### ISSUE THREAD

**Issue by svipas** [santoso-wijaya/vscode-helios-selene#16]
As you can see in the screenshot below it's hard to distinguish what was actually written and what inline suggestion I have.

I wrote `git comm` and I got rest as a inline suggestion, but it is hard to tell. Editor handles it better, because it uses italic style, maybe it makes sense to use it here as well if it supports?

![image](https://github.com/santoso-wijaya/vscode-helios-selene/assets/10441177/99e8643d-9d12-4097-b6ea-51a13b0294a0)

**Comment by santoso-wijaya** [comment]
I don't see any terminal specific settings for inlay hint colors, but I did set it for the editor generally. If it doesn't affect the terminal, can you see if the workaround referenced [here](https://github.com/microsoft/vscode/issues/171712#issuecomment-1396864957) works for you?
