### ISSUE TITLE
[Helios Solarized Light] Selection highlight doesn't work in "Developer: Inspect Editor Tokens and Scopes"

### ISSUE THREAD

**Issue by svipas** [santoso-wijaya/vscode-helios-selene#18]
<img width="420" alt="image" src="https://github.com/santoso-wijaya/vscode-helios-selene/assets/10441177/2f15a339-b710-4c68-aac6-230d086e0214">

You can select in this view, but you can't see, but it works if you select something and do CMD+C and then CMD+V it will paste. Seems like selection highlighting is broken here.

**Comment by santoso-wijaya** [comment]
I had to darken it (lighten it in dark mode) a bit, because the current background shade was clashing with the selection background color (hence ... invisible selection highlighting).

**Comment by svipas** [comment]
Tested with 0.3.3 and now I can see selection highlight, thank you!
