### ISSUE TITLE
[Helios Solarized Light] Missing syntax highlighting for Go

### ISSUE THREAD

**Issue by svipas** [santoso-wijaya/vscode-helios-selene#19]
I checked it out and I see that in Go keywords aren't highlighted. Probably other stuff is missing highlight as well. Best would be to also install Go extension: https://marketplace.visualstudio.com/items?itemName=golang.Go and check out if theme works well for Go.

**Comment by santoso-wijaya** [comment]
Maybe caused by an unrelated bug in the golang extension or vscode? I can't even open the token inspector, with a "semantictokens are disabled" error:

![image](https://github.com/santoso-wijaya/vscode-helios-selene/assets/157527329/3b820ed7-8825-45a3-9e52-25ecf9b8d12f)
