### ISSUE TITLE
[Helios Solarized Light] `variable.defaultLibrary` missing color

### ISSUE THREAD

**Issue by svipas** [santoso-wijaya/vscode-helios-selene#20]
<img width="121" alt="image" src="https://github.com/santoso-wijaya/vscode-helios-selene/assets/10441177/59e4ecc3-9924-4864-b0ac-23f0a9f38d0b">

As you can see `Math` is without color, but `Promise` is.

- **Math**: `variable.defaultLibrary`
- **Promise**: `class.defaultLibrary`

So seems like `variable.defaultLibrary` is missing.

**This is inside JS/TS file.**

**Comment by santoso-wijaya** [comment]
Huh. The textmate token scope for `Math` was correct in identifying a "class" and would've colored it accordingly, but the semantic token parser identifies it as a built-in library and overrides it.

I haven't thought about what color to assign semantic builtin variables (hence, the default shade), but I can make it match with builtin classes (green) for now.

![image](https://github.com/santoso-wijaya/vscode-helios-selene/assets/157527329/53f5ce2a-51e3-4715-830c-6e0d5eb14655)
