### ISSUE TITLE
[Helios Solarized Light] Terminal color hard to read

### ISSUE THREAD

**Issue by svipas** [santoso-wijaya/vscode-helios-selene#21]
**Helios Solarized Light**

<img width="356" alt="image" src="https://github.com/santoso-wijaya/vscode-helios-selene/assets/10441177/9c1472e1-6ada-4f39-8529-2e114c2a97b7">

<hr>

In **Selene Selenized Light** it is easier to read text on blue background:

<img width="345" alt="image" src="https://github.com/santoso-wijaya/vscode-helios-selene/assets/10441177/9fa83e44-a05e-48c3-8420-1d2fef205a29">

<hr>

Not sure though which one is more correct, but I would love if this could be improved.

**Comment by santoso-wijaya** [comment]
This one has been perplexing me for a while, too. There is nothing different between solarized and selenized variants (light theme), config wise.

The color scheme only defines what the terminal ansi colors palette is: [link](https://github.com/santoso-wijaya/vscode-helios-selene/blob/a2cd2e1d3861798e1760c1a4bce6a3fe53616815/themes/common/workbench-colors.json.liquid#L192-L214). How those colors are used are up to the prompt app that you use (if tmux is used, etc).

For me, I use Starship. In a terminal emulator _outside_ of VS Code, this is what my prompt looks like:

![image](https://github.com/santoso-wijaya/vscode-helios-selene/assets/157527329/fe3d0bba-1275-417e-88b2-022d286e05ca)

In VSCode's terminal emulator, I also use the same Starship prompt, with **identical** configurations, but for some reason VS Code's terminal emulator decides to flip some of the foreground colors on me (this is on Selenized light):

![image](https://github.com/santoso-wijaya/vscode-helios-selene/assets/157527329/79d5e4f3-b806-4ba2-a443-bb0ca5f23b0f)

**Comment by svipas** [comment]
Interesting, but why then `Selene Selenized Light` have white foreground and `Helios Solarized Light` has black foreground?

**Comment by santoso-wijaya** [comment]
Right, there's something that the terminal emulator (and/or the specific tmux/whatever prompt app is layered on top) is doing with the color palette, some sort of dynamic recomputation that is currently opaque to me.

As you can see, in my Starship prompt setup, in Selenized Light, Starship chose a black foreground for some components of the prompt--despite my `Starship.toml` file specifying a white-ish foreground rgb value.

I'll dig around occasionally when my curiosity piques, but for now I don't have a workaround yet.

**Comment by scottinet** [comment]
Maybe this is what is modifying the terminal colors?
https://code.visualstudio.com/docs/terminal/appearance#_minimum-contrast-ratio

**Comment by santoso-wijaya** [comment]
> Maybe this configuration is what is modifying the terminal colors? https://code.visualstudio.com/docs/terminal/appearance#_minimum-contrast-ratio

!! Thank you!

The setting isn't part of the color theme, but a user/workspace configuration. Setting this value to `1` fixes things as you'd expect:

![image](https://github.com/santoso-wijaya/vscode-helios-selene/assets/157527329/69a796c3-c466-4d61-b6fb-881d2600c7c8)
