### ISSUE TITLE
[Helios Solarized Light] `new` & built-in library italics

### ISSUE THREAD

**Issue by svipas** [santoso-wijaya/vscode-helios-selene#22]
- I noticed that `new` keyword doesn't have color again, probably was lost since bunch of changes were made to fix JS/TS coloring.

<img width="74" alt="image" src="https://github.com/santoso-wijaya/vscode-helios-selene/assets/10441177/6ced8498-0a18-4187-9fc4-ac1835f9b461">

- Additionally, I saw that built-in library methods and classes are italics - for e.g. `Array.isArray()` both of them are italic. I guess the intention was to use italic for `Array`, but question is does it really make sense to have italic there? I guess that is a way to distinguish easier between custom code & built-in, but I'm not quite sure if it really makes sense to use italic.

<img width="142" alt="image" src="https://github.com/santoso-wijaya/vscode-helios-selene/assets/10441177/913e7738-96fd-4c33-b55f-eb4dfc88f62f">

<img width="193" alt="image" src="https://github.com/santoso-wijaya/vscode-helios-selene/assets/10441177/acbe42d2-6089-45fa-ac82-13ba47809cae">

<img width="73" alt="image" src="https://github.com/santoso-wijaya/vscode-helios-selene/assets/10441177/fce2ad37-f070-4046-9c34-8c4b61e33560">

**Comment by santoso-wijaya** [comment]
Sharp eye!

The `new` regression was caused by 28c017d66a5afe9ee6ba47b9e4b4e7f8bc5310dc. I wanted to remove the color from regular operators (`+`, `-`, etc) but that inadvertently affected `new` as it is also a subtype of operators. My next commit should resolve this.

**Comment by santoso-wijaya** [comment]
As for the builtin library italics, I did want to italicize builtins to distinguish them a bit. I scoped them down to just types, classes, and interfaces now.

If you still want to disable italicizing them at all, you can add this in your `settings.json` file:

```json
"editor.semanticTokenColorCustomizations": {
  "rules": {
    "*.defaultLibrary": {
      "italic": false
    }
  }
}
```
