### ISSUE TITLE
Publish to Open VSX

### ISSUE THREAD

**Issue by 0rzech** [santoso-wijaya/vscode-helios-selene#23]
Would you consider publishing this extensions on [Open VSX](https://open-vsx.org/)?

AFAIK, VSCode markeplate ToS forbid using it with other editors. By publishing the extension on Open VSX, you would make it available to [Theia IDE](https://theia-ide.org/), [VSCodium](https://vscodium.com/) etc.

Instructions on how to publish to Open VSX are [here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions).

**Comment by santoso-wijaya** [comment]
Published: https://open-vsx.org/extension/santoso-wijaya/helios-selene

**Comment by 0rzech** [comment]
🚀 Thank you very much!

**Comment by 0rzech** [comment]
Thank you very much!
